# Generated by Django 3.0.3 on 2020-07-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ab_data',
            name='sourcinginstockstatus',
        ),
    ]
