# Generated by Django 3.0.3 on 2020-07-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0002_remove_ab_data_sourcinginstockstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ab_data',
            name='runtime',
            field=models.TimeField(blank=True, max_length=100, null=True),
        ),
    ]
