# Generated by Django 3.0.3 on 2020-07-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0003_auto_20200705_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='ab_data',
            name='Inventory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
