# Generated by Django 3.0.3 on 2020-07-06 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0004_ab_data_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AB_sitestatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.SlugField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ASIN')),
                ('sitestatus', models.CharField(max_length=20)),
                ('allocatedto', models.CharField(max_length=20)),
            ],
        ),
    ]
