# Generated by Django 3.0.3 on 2020-07-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0005_ab_sitestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ab_data',
            name='blacklist_reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
