# Generated by Django 3.0.3 on 2020-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0008_hcsavings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hcsavings',
            name='hcsavings',
            field=models.FloatField(),
        ),
    ]
