# Generated by Django 3.0.3 on 2020-07-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0009_auto_20200712_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ab_data',
            old_name='blacklist_reason',
            new_name='Boss_status_user',
        ),
        migrations.RenameField(
            model_name='ab_data',
            old_name='blacklist_user',
            new_name='Bossed_reason',
        ),
    ]
