# Generated by Django 3.0.3 on 2020-07-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0010_auto_20200712_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ab_data',
            old_name='Boss_status_user',
            new_name='bossed_user',
        ),
    ]
