# Generated by Django 3.0.3 on 2020-08-07 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0011_auto_20200712_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ab_data',
            old_name='Bossed_reason',
            new_name='bossed_reason',
        ),
        migrations.AlterField(
            model_name='ab_troubleshooting',
            name='asin',
            field=models.SlugField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ASIN'),
        ),
    ]
