# Generated by Django 3.0.3 on 2020-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0012_auto_20200807_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='ab_troubleshooting',
            name='runstatus',
            field=models.CharField(blank=True, default='run', max_length=20, null=True),
        ),
    ]
