# Generated by Django 3.0.3 on 2020-08-15 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0013_ab_troubleshooting_runstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ab_data',
            name='allocationdate',
            field=models.DateField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
