# Generated by Django 3.0.3 on 2020-08-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABapp', '0014_ab_data_allocationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ab_data',
            old_name='asin1',
            new_name='asin',
        ),
        migrations.RenameField(
            model_name='ab_data',
            old_name='buyability_trace',
            new_name='buyability_status',
        ),
    ]
